import Head from "next/head";
import Image from "next/image";

import Nav from "@/components/Nav";
import todo from "../assests/todocolor.svg";
import womencalender from "../assests/womencalender.svg";


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>ThingsToDo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>


      <main className="p-4 ">
        <Nav />
        <div className="md:space-x-2 lg:space-x-10 mt-10 flex flex-col sm:flex-row sm:justify-center sm:space-x-6 items-center space-y-10">
          <div className="w-full max-w-[400px] md:max-w-[500px] space-y-2 md:space-y-3">
            <p className=" text-center font-extrabold text-[30px]  sm:text-start md:text-[38px]"> <span className=" text-[#5271ff]">ThingsToDo</span> helps you acheive your goals</p>
            <p className="text-center opacity-60 text-sm md:text-base md:max-w-[350px] sm:text-start  ">
              {" "}
              Whether you're a student, professional, or someone looking to
              improve their productivity, this todo app is the perfect tool to
              help you achieve your goals and stay organized.
            </p>
            <div className="flex justify-center sm:justify-start pt-3">
            <button className="border py-2 px-6 bg-[#5271ff] text-white rounded-lg">Get Started</button>
        </div>
          </div>
          
          <div className="flex flex-col ">
            <Image src={todo} width={100} height={100}  className='w-[250px] md:w-[350px] '/>
            <Image src={womencalender} width={100} height={100}  className=' hidden md:inline w-[250px]  md:w-[350px]'/>
          </div>
        </div>
      </main>
    </div>
  );
}
