import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Nav from "@/components/Nav";
import CalenderImg from "../assests/calender.svg";
import todo from "../assests/todo.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>ThingsToDo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 ">
        <Nav />
        <div className="mt-10 flex flex-col sm:flex-row sm:justify-center sm:space-x-6 items-center space-y-10">
          <div className="w-full max-w-[400px] space-y-2">
            <p className="font-bold text-[30px] text-center"> <span className=" text-blue-600">ThingsToDo</span> helps you acheive your goals</p>
            <p className="text-center  opacity-60 text-sm">
              {" "}
              Whether you're a student, professional, or someone looking to
              improve their productivity, this todo app is the perfect tool to
              help you achieve your goals and stay organized.
            </p>
          </div>
          <div>
            <Image src={todo} width={100} height={100}  className='w-[250px]'/>
          </div>
        </div>
      </main>
    </div>
  );
}
